{
 "title": "AWS Environment Daily Cost - Manual -",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "2h",
 "panels": [
  {
   "title": "Today's Costs",
   "type": "graph",
   "gridPos": { "h": 16, "w": 17, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "currencyUSD", "label": "Cost" }
   ],
   "targets": [
    {
     "expr": "aws_daily_cost",
     "legendFormat": "<b style='font-weight: 800; font-size: 2.5rem; font-family: \"Comic Sans MS\", cursive, sans-serif;'>{{environment}}</b>"
    }
   ]
  },
  {
   "title": "Today's Total Costs",
   "type": "singlestat",
   "gridPos": { "h": 16, "w": 7, "x": 17, "y": 0 },
   "format": "currencyUSD",
   "valueName": "max",
   "targets": [
    { "expr": "sum(aws_daily_cost)" }
   ]
  },
  {
   "title": "AWS Daily Cost per Environment",
   "type": "graph",
   "description": "Daily Cost for all AWS environments",
   "gridPos": { "h": 14, "w": 17, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "currencyUSD", "label": "Daily Cost ($)" }
   ],
   "targets": [
    {
     "expr": "max_over_time(aws_daily_cost[1d])",
     "legendFormat": "{{environment}}"
    }
   ]
  },
  {
   "title": "Monthly Total Costs",
   "type": "singlestat",
   "gridPos": { "h": 14, "w": 7, "x": 17, "y": 16 },
   "format": "currencyUSD",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(max_over_time(aws_daily_cost[1d]))"
    }
   ]
  }
 ]
}